select 
    _sdc_batched_at       , 
    _sdc_extracted_at     , 
    _sdc_received_at      ,  
    _sdc_sequence         , 
    _sdc_table_version    , 
    chatenabled           , 
    combinedshipmethodid  , 
    combinedshippingpolicy, 
    contentprovider       , 
    countenabled          , 
    createdat             , 
    id                    , 
    isapplive             , 
    isautodropenabled     , 
    ishidden              , 
    ordering              , 
    secondaryshowtype     , 
    selectedvodtype       , 
    showdatetype          , 
    showstate             , 
    showtilecolors        , 
    showtype              , 
    sponsored             , 
    starttime             , 
    streampath            , 
    title                 , 
    updatedat             , 
    viewenabled           , 
    agerestriction        , 
    recordpath            , 
    festivalrefid         , 
    uploadpath            , 
    activated_at          , 
    removedat             , 
    horizontalimage       , 
    teaservideo           , 
    location              , 
    endtime               , 
    teaserlengthseconds   , 
    vodlengthseconds      
from {{ source('ntwrk_prod_aws', 'dl_show') }}