SELECT
    _sdc_batched_at            ,      
    _sdc_extracted_at          ,      
    _sdc_received_at           ,      
    _sdc_sequence              ,      
    _sdc_table_version         ,      
    addressid                  ,      
    chargeid                   ,      
    createdat                  ,      
    createdon                  ,      
    customerid                 ,      
    id                         ,      
    idempotencykey             ,      
    modifiedon                 ,      
    orderid                    ,      
    ordernumber                ,      
    paymentmethod              ,      
    quantity                   ,      
    shipmethodid               ,      
    showid                     ,      
    sourcetoken                ,      
    status                     ,      
    type                       ,      
    variantid                  ,      
    updatedat                  ,      
    inventorychangelogid       ,      
    paymentprocessinginfo      ,      
    orderstatusurl             ,      
    confirmationemailsent      ,      
    thirdpartyinventorysyncstartedat, 
    thirdpartyinventorysyncstatus   , 
    orderrefidstr                   , 
    totalprice                      , 
    raffleentryid                   , 
    info                            , 
    paymentmethodid                 , 
    fulfillmentstatus               , 
    appliedcustomercredit           , 
    inventoryupdateinfo             , 
    variantprice                    , 
    orderrefid                      , 
    totaldiscount                    
from {{ source('ntwrk_prod_aws', 'dl_transaction') }}